const express = require('express')
const router = express.Router()

const Users = require('./users/users')
const Stores = require('./stores/stores')
const Products = require('./products/products')
const Watt = require('./power/power')

router
    .post('/login', Users.LOGIN)
    .get('/users', Users.ALL_USERS)
    .post('/newUser', Users.CREATE_USER)
    .put('/updateUser', Users.UPDATE_USER)
    .delete('/deleteUser', Users.DELETE_USER)
    .get('/stores', Stores.ALL_STORES)
    .post('/newStore', Stores.NEW_STORE)
    .put('/updateStore', Stores.UPDATE_STORE)
    .delete('/deleteStore', Stores.DELETE_STORE)
    .post('/sendStoreMoney', Stores.SEND_STORE_MONEY)
    .get('/products', Products.ALL_PRODUCTS)
    .post('/newProduct', Products.NEW_PRODUCT)
    .post('/productStore', Products.PRODUCTS_STORE)
    .get('/getCasherMoney', Stores.GET_CASHER_MONEY)
    .post('/sendToAccountant', Stores.SEND_TO_ACCOUNTANT)
    .get('/getAccountantMoney', Stores.GET_ACCOUNTANT_MONEY)
    .post('/monthlyReport', Stores.MONTHLY_REPORT)
    .get('/power', Watt.GET)
    .put('/updatePrice', Watt.PUT)
    .get('/accountantMonthly', Stores.MONTHLY_REPORT_ACCOUNTANT)
    .get('/warehouseDaily', Products.GET_DAILY_SALE_WARE_HOUSE_MAN)

module.exports = router